name: Deploy Images to GHCR
 
env:
  DOTNET_VERSION: '1.0.1'
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
 
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
 
          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/${{username}}/lx-music-sync-server:latest
              docker push ghcr.io/${{username}}/lx-music-sync-server:latest
